name: coinplus_db
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  provider: ^6.0.5
  firebase_auth: ^4.14.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.13.3
  nfc_manager: ^3.2.0
  flutter_hooks: ^0.20.3
  styled_text: ^8.1.0
  gap: ^3.0.0
  flutter_scale_tap: ^1.0.5
  nxp_originality_verifier: ^0.0.6
  lottie: ^2.4.0
  auto_route: ^7.3.2
  shared_preferences: ^2.2.2


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_driver:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mobx_codegen: ^2.2.0
  collection: ^1.17.1
  auto_route_generator: ^7.1.1
  freezed: ^2.3.2



  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/animated_logo/nfcanimation.json
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RedHatMedium
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
